import pygame
import math
import pygame_menu

pygame.display.init()

GAME_TITLE = 'SPACE GOLF'

LEVELS_FOLDER = 'levels'

# infoObject = pygame.display.Info()

SCREEN_WIDTH = 1800  # infoObject.current_w
SCREEN_HEIGHT = 900  # infoObject.current_h

MENU_WIDTH = SCREEN_WIDTH - 100
MENU_HEIGHT = SCREEN_HEIGHT - 100
TITLE_COLOUR = (212, 205, 0)
SUB_TEXT_COLOUR = (255, 255, 255)
SUB_TEXT_SIZE = 20
TITLE_SIZE = 50
MENU_TEXT_SIZE = 35
LEADERBOARD_COLOUR = (168, 168, 168)

LEADERBOARD_MENU_WIDTH = MENU_WIDTH - 100
LEADERBOARD_MENU_HEIGHT = MENU_HEIGHT - 100
AIMING = False

MAX_LEVELS = 3

POWER_BOX_COLOUR = (255, 255, 255)
POWER_BOX_HEIGHT = 40
POWER_BOX_WIDTH = 310
POWER_BOX_X = SCREEN_WIDTH // 2 - POWER_BOX_WIDTH // 2
POWER_BOX_Y = SCREEN_HEIGHT - 100

POWER_BAR_COLOUR = (255, 0, 0)
POWER_BAR_HEIGHT = 40
POWER_BAR_WIDTH = 20
POWER_BAR_X_INITIAL_X = POWER_BOX_X + POWER_BOX_WIDTH // 2
POWER_BAR_X = POWER_BOX_X + POWER_BOX_WIDTH // 2
POWER_BAR_Y = SCREEN_HEIGHT - 150

MAX_DISPLACEMENT = POWER_BOX_X - POWER_BAR_X
TIME_PERIOD = 5
FREQUENCY = 1 / 3
OMEGA = (2 * (math.pi) * FREQUENCY)

HOLE_RETURN_WIDTH = 20
HOLE_RETURN_HEIGHT = HOLE_RETURN_WIDTH

BLACK_HOLE_RETURN_WIDTH = 40
BLACK_HOLE_RETURN_HEIGHT = BLACK_HOLE_RETURN_WIDTH

TILE_HEIGHT = SCREEN_HEIGHT * 0.6
TILE_WIDTH = 2 * TILE_HEIGHT
TILE_Z_HEIGHT = TILE_HEIGHT
TILE_START_X = SCREEN_WIDTH // 2
TILE_START_Y = SCREEN_HEIGHT // 4 - 40
TILE_RETURN_X = SCREEN_WIDTH // 2
TILE_RETURN_Y = SCREEN_HEIGHT // 4 - 40

STAR_MIN_RADIUS = 1
STAR_MAX_RADIUS = 2

STAR_COLOUR = (255, 255, 255)

MINIMAP_WIDTH = 120
MINIMAP_HEIGHT = 120
MINIMAP_START_X = 20
MINIMAP_START_Y = 20
MINIMAP_MARGIN = 10
MINIMAP_BALL_RADIUS = 4

TILE_BALL_RADIUS = 6
TILE_BALL_COLOUR = (255, 255, 255)
TILE_SHADOW_RADIUS = 2
TILE_SHADDOW_COLOUR = (0, 0, 0)
BALL_MAX_SPEED = 20
BALL_INIT_SPEED = 20
BALL_MIN_SPEED = 1
BALL_INCREMENT_SPEED = 5
BALL_INIT_FLIGHT_ANGLE = 0

# Ball_info text
TEXT_COLOUR = (255, 255, 255)
TEXT_BOX_WIDTH = 200
TEXT_BOX_HEIGHT = 35
TEXT_BOX_GAP = 10
TEXT_BOX_WIDTH_GAP = 40
SHIFT_RIGHT = TEXT_BOX_WIDTH // 10
TEXT_BOX_X = SCREEN_WIDTH - TEXT_BOX_WIDTH - TEXT_BOX_WIDTH_GAP
TEXT_BOX_Y = 2 * SCREEN_HEIGHT // 3
TEXT_BOX_COLOUR = (102, 102, 102)

LEVEL_NAME_TEXT_BOX_START_X = TEXT_BOX_X
LEVEL_NAME_TEXT_BOX_START_Y = TEXT_BOX_HEIGHT
LEVEL_NAME_TEXT_BOX_WIDTH = 50
LEVEL_NAME_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

LEVEL_NUMBER_TEXT_BOX_START_X = TEXT_BOX_X
LEVEL_NUMBER_TEXT_BOX_START_Y = LEVEL_NAME_TEXT_BOX_START_Y + 50
LEVEL_NUMBER_TEXT_BOX_WIDTH = 50
LEVEL_NUMBER_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

LEVEL_GRAVITY_TEXT_BOX_START_X = TEXT_BOX_X
LEVEL_GRAVITY_TEXT_BOX_START_Y = LEVEL_NUMBER_TEXT_BOX_START_Y + 50
LEVEL_GRAVITY_TEXT_BOX_WIDTH = 50
LEVEL_GRAVITY_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

LEVEL_SURFACE_TEXT_BOX_START_X = TEXT_BOX_X
LEVEL_SURFACE_TEXT_BOX_START_Y = LEVEL_GRAVITY_TEXT_BOX_START_Y + 50
LEVEL_SURFACE_TEXT_BOX_WIDTH = 50
LEVEL_SURFACE_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

PLAYER_NAME_TEXT_BOX_START_X = TEXT_BOX_GAP
PLAYER_NAME_TEXT_BOX_START_Y = 2 * SCREEN_HEIGHT // 3
PLAYER_NAME_TEXT_BOX_START_WIDTH = 100
PLAYER_NAME_TEXT_BOX_START_HEIGHT = TEXT_BOX_HEIGHT

PAR_TEXT_BOX_X = PLAYER_NAME_TEXT_BOX_START_X
PAR_TEXT_BOX_Y = PLAYER_NAME_TEXT_BOX_START_Y + 50
PAR_TEXT_BOX_WIDTH = 50
PAR_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

STROKE_COUNT_TEXT_BOX_X = PLAYER_NAME_TEXT_BOX_START_X
STROKE_COUNT_TEXT_BOX_Y = PAR_TEXT_BOX_Y + 50
STROKE_COUNT_TEXT_BOX_WIDTH = 50
STROKE_COUNT_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

TOTAL_STROKE_COUNT_TEXT_BOX_X = PLAYER_NAME_TEXT_BOX_START_X
TOTAL_STROKE_COUNT_TEXT_BOX_Y = STROKE_COUNT_TEXT_BOX_Y + 50
TOTAL_STROKE_COUNT_TEXT_BOX_WIDTH = 50
TOTAL_STROKE_COUNT_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

CLUB_TEXT_BOX_X = PLAYER_NAME_TEXT_BOX_START_X
CLUB_TEXT_BOX_Y = TOTAL_STROKE_COUNT_TEXT_BOX_Y + 50
TOTAL_STROKE_COUNT_TEXT_BOX_WIDTH = 50
TOTAL_STROKE_COUNT_TEXT_BOX_HEIGHT = TEXT_BOX_HEIGHT

MAXIMUM_X = 200
MAXIMUM_Y = 200
MAXIMUM_Z = 200

DELTA_ROTATION_ANGLE = 10
DELTA_FLIGHT_ANGLE = 5

TIME_INTERVAL = 0.1

COAFFICENT_OF_RESTITUTION = 0.7

HOLE_ANGLE = 0
HOLE_DELTA_ANGLE = 0.05

pygame.font.init()
MENU_FONT = pygame_menu.font.FONT_8BIT
LEARDERBOARD_FONT = pygame_menu.font.FONT_BEBAS

FONT_COLOUR = (255, 255, 255)
TEXT_SIZE = 30
START_X = 1300
START_Y = 50
GAP = 40

M_COLOUR = (122, 122, 11)
radius = 20

MYSTERY_BOX_WIDTH = 9
MYSTERY_BOX_VELOCITY = 5

GOOD_MYSTERY_BOX_COLOUR = (2, 166, 18)
BAD_MYSTERY_BOX_COLOUR = (2, 24, 166)
TILE_MOVE = 1

DRIVER_MAX_SPEED = 20
DRIVER_RETURN_MAX_SPEED = 20

PUTTER_MAX_SPEED = 5
PUTTER_RETURN_MAX_SPEED = 5

IRON_MAX_SPEED = 13
IRON_RETURN_MAX_SPEED = 13

LEVEL_TREE = {
    "level_name": "Earth",
    "children":
        [
            {
                "level_name": "Pluto",
                "children":
                
                    [
                        {"level_name": "Mars",
                         "children":
                             [
                                 {
                                    "level_name": "Venus"
                                 },
                                 {
                                    "level_name": "Mercury"
                                 }
                             ]
                         },
                        {
                            "level_name": "Saturn"
                        },
                        {
                            "level_name": "Neptune"
                        }
                    ]
            },
            {
                "level_name": "Jupiter"
            }
        ]
}


